services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: footballzone-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: footballzone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: footballzone123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - footballzone-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d footballzone"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: footballzone-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - footballzone-network
    command: redis-server --appendonly yes --requirepass "redis123"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  footballzone-network:
    driver: bridge